language: node_js
node_js:
  - 10.14.1
cache:
  npm: true
  directories:
    - node_modules
before_install:
  - npm install -g npm
branches:
  only:
    - thai-nguyen-staging
install:
  - npm install
before_script:
script:
  - echo "skipping tests"
before_deploy:
  - npm run build
deploy:
  provider: heroku
  app: webauth-i-challenge-tn
  api_key:
    secure: KIjjpVQGEf7ZXJqLwsDAj0uZUVy+/Inh7msZzifK9YjUaoV6gL9WdVnpWGcobS3hOJjdDdiyioWzcB6KJZ9F5VqBKD1+tEo2hGaS7vBKkVswjQMJWRwpRBPb1s55fjF3jTBOySMoJl1OlkIVwLJe+Ze8ad6IPpd/j83l/2YkEoztM1kk9DTfqKhLIaztB9Zck8jzKbR3r3R9lpRjzK3oqYJSbZUuVXGvF8e1FtvGyYEzBMkH78852FmTcAhuVSNs2XHupWzLJlSefc7kmH50WksCSduGjBnhJc92d2Ob9almz2L/NxF1HgPH4A6hIfE+9+GFCRIrhmxO+Szm2sUKCLcid/XK1IKi+OI7VoKgFo2z7aq6eE8BZTamokOnQh7ENKkc4R/3TeT7eFzAUQ3ctoDhA/EdaTy0f18GKMRSSUbKPU2VWdWcQkEe8GqCa8/dhuQnQIYaa126iOxKgWiufw+MKQLTVFteSF+r85fbL/EOnYvFZfBWUn3M9xsVI+7gT9UPnCetdELyQT+z8czJN87hFCpS7TB6y0WpCjkUmIVWoaqhPm320ohz9Lsadc9wlYOijkCtC5R4bSs9Hed5w0ZLWRy96bNdArAQtA8TSpbyhmxfDSZ9XXFFZ/MyDxBroSNkrSi4kA9Wy6RxsphZFuDJ55TDua8ayOQdeLknQdc=
  on:
    branch: thai-nguyen-staging
after_deploy:
after_script:
