const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";
const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
const REGISTRATION_FAILURE = "REGISTRATION_FAILURE";
const LOGOUT = "LOGOUT";
const SET_IS_LOADING = "SET_IS_LOADING";

export {
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  REGISTRATION_SUCCESS,
  REGISTRATION_FAILURE,
  LOGOUT,
  SET_IS_LOADING
};
